### ISSUE TITLE
Convert REST queries to GraphQL

### ISSUE THREAD

**Issue by echjordan** [electron/repos-using-electron#26]

**Comment by echjordan** [comment]
@gr2m getting "Must have push access to view repository collaborators." error when querying for collaborators, assuming this is the same as the REST 'contributors' field...is there a workaround?

**Comment by gr2m** [comment]
How do you authenticate? Do you use a personal access token or is it coming from a GitHub app?

**Comment by echjordan** [comment]
Personal access token at the moment

**Comment by gr2m** [comment]
Can you share the query that you send?

I tried this and it worked just fine

```graphql
{
  repository(owner: "octokit", name:"rest.js") {
    collaborators(first: 10) {
      nodes {
        login
      }
    }
  }
}
```

**Comment by gr2m** [comment]
see https://developer.github.com/v4/explorer/?query=%7B%0D%0A%20%20repository%28owner%3A%20%22octokit%22%2C%20name%3A%22rest.js%22%29%20%7B%0D%0A%20%20%20%20collaborators%28first%3A%2010%29%20%7B%0D%0A%20%20%20%20%20%20nodes%20%7B%0D%0A%20%20%20%20%20%20%20%20login%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Comment by echjordan** [comment]
Tried the same query signed in under my personal account in the explorer and got the same error
`{
  "data": {
    "repository": {
      "collaborators": null
    }
  },
  "errors": [
    {
      "message": "Must have push access to view repository collaborators.",
      "type": "FORBIDDEN",
      "path": [
        "repository",
        "collaborators"
      ],
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ]
}`

**Comment by gr2m** [comment]
can you try to change the `repository(owner: "octokit", name:"rest.js")` part and set it to an owner/name of a repository where you have admin access? e.g. try `repository(owner: "echjordan", name:"test_repo")`

**Comment by zeke** [comment]
@echjordan we can also punt on getting a contributor list if necessary. Not a deal-breaker. Just nice data to have.

**Comment by echjordan** [comment]
@gr2m @zeke  oh yes yes of course it works with proper permissions. I was thinking about how this issue would play out in production and thinking there was some magic work around I was missing. with the proper pemissions taken care of, the query works just fine -- sorry!!!

**Comment by gr2m** [comment]
no worries at all :)
